/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CadastroClienteComponent: typeof import('./src/components/CadastroClienteComponent.vue')['default']
    CadastroClienteDialog: typeof import('./src/components/CadastroClienteDialog.vue')['default']
    CadastroVestido: typeof import('./src/components/Vestido/CadastroVestido.vue')['default']
    CadastroVestidoComponent: typeof import('./src/components/Vestido/CadastroVestidoComponent.vue')['default']
    ComponentTeste: typeof import('./src/components/ComponentTeste.vue')['default']
    ConsultaClienteComponent: typeof import('./src/components/ConsultaClienteComponent.vue')['default']
    ConsultaVestido: typeof import('./src/components/Vestido/ConsultaVestido.vue')['default']
    ConsultaVestidoComponent: typeof import('./src/components/Vestido/ConsultaVestidoComponent.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    HomeComponent: typeof import('./src/components/HomeComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackBarComponent: typeof import('./src/components/SnackBarComponent.vue')['default']
  }
}
